name = "notion-to-r2-worker"
main = "worker.js"
compatibility_date = "2025-03-05"
nodejs_compat = true

# Trigger the worker on a schedule (every day at 5:00 AM UTC)
# Adjust the cron pattern as needed
[triggers]
crons = ["0 5 * * *"]

# R2 bucket binding - this connects the R2 bucket to your worker
[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "blog-data"

# Environment variables
[vars]
# Secrets are set using wrangler secret commands
# NOTION_DATABASE_ID is set as a secret

# Node module configuration - properly handle Node.js modules
[build]
command = "npm install"

[[rules]]
type = "CommonJS"
globs = ["**/*.js"]

# Enable Workers Logs for observability
[observability]
enabled = true
head_sampling_rate = 1 # Set to 1 to log 100% of requests
